/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * welcomePanel.java
 *
 * Created on Apr 8, 2010, 7:52:01 PM
 */

package restaurant;

/**
 *
 * @author l
 */
public class welcomePanel extends javax.swing.JPanel {

    /** Creates new form welcomePanel */
    public welcomePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        orderLable = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        welcomePanel.setName("welcomePanel"); // NOI18N

        welcomeLabel.setFont(welcomeLabel.getFont().deriveFont(welcomeLabel.getFont().getSize()+100f));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(restaurant.RestaurantApp.class).getContext().getResourceMap(welcomePanel.class);
        welcomeLabel.setText(resourceMap.getString("welcomeLabel.text")); // NOI18N
        welcomeLabel.setName("welcomeLabel"); // NOI18N

        orderLable.setFont(orderLable.getFont().deriveFont(orderLable.getFont().getSize()+30f));
        orderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderLable.setText(resourceMap.getString("orderLable.text")); // NOI18N
        orderLable.setName("orderLable"); // NOI18N
        orderLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderLableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderLableMousePressed(evt);
            }
        });

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderLable, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLableMouseClicked
        // TODO add your handling code here:
        RestaurantView.clearScreen();
        this.getRootPane().setContentPane(RestaurantApp.customerP);
        RestaurantApp.customerP.setVisible(true);
}//GEN-LAST:event_orderLableMouseClicked

    private void orderLableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLableMousePressed
        // TODO add your handling code here:
        RestaurantView.clearScreen();
        this.getRootPane().setContentPane(RestaurantApp.customerP);
        RestaurantApp.customerP.setVisible(true);
}//GEN-LAST:event_orderLableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel orderLable;
    public static javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

}
